config/routes.rb
Rails.application.routes.draw do

  resources :arduino_clients
  resources :registration_courses
  resources :disciplines
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, except: [:create]
  resources :cursos
  resources :cameras

  root to: 'welcome#index'

  scope "/cameras/:id/" do
    get "camera_record", to: "cameras#record", as: :camera_record
    get "camera_record_start", to: "cameras#record_start", as: :camera_record_start
    get "camera_record_stop", to: "cameras#record_stop", as: :camera_record_stop
  end

  resources :disciplines do
    get :arduino
  end

  get 'welcome/index'

  get 'welcome/destroy'

  get 'welcome/edit'

  get 'welcome/show'

  post 'create_user' => 'users#create', as: :create_user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:aluno, :professor, :coordenador, :administrador]

  belongs_to :curso, :dependent => :destroy
  belongs_to :discipline, :dependent => :destroy
  belongs_to :registration_course, :dependent => :destroy

  validates :nome, presence: true

  def course_exists?(course_id)
    RegistrationCourse.exists?(curso_id: course_id, aluno_id: self.id)
  end

  def forem_name
    nome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :verify_permission!, except: [:index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    authorize @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user

      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def verify_permission!
      roles_permited = ['coordenador', 'administrador']
      roles_not_permited = ['aluno', 'professor']

      if (current_user.id == @user.id && roles_not_permited.include?(current_user.role)) || roles_permited.include?(current_user.role)
        true
      else
        user_not_authorized
        false
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :email, :password, :password_confirmation, :current_password, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, url: create_user_path do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h3>Sign up</h3>
    <div class="form-group">
      <%= f.label :nome %>
      <%= f.text_field :nome, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :perfil %>
      <% if current_user.role == 'administrador' %>
        <%= f.select :role, options_for_select([["Aluno", "aluno"], ["Professor", "professor"], ["Coordenador", "coordenador"], ["Administrador", "administrador"]], params[:role])%>
      <% elsif current_user.role == 'coordenador' %>
        <%= f.select :role, options_for_select([["Aluno", "aluno"], ["Professor", "professor"]], params[:role])%>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, :autofocus => false, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
     <%= f.submit :class => 'button right' %>
<% end %>

app/views/users/edit.html.erb
<div class="authform">
  <h1>Editing User</h1>
  <%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h3>Sign up</h3>
    <div class="form-group">
      <%= f.label :nome %>
      <%= f.text_field :nome, :autofocus => true, class: 'form-control' %>
    </div>
    <% if current_user.role == 'administrador' || current_user.role == 'coordenador' %>
        <div class="form-group">
          <%= f.label :perfil %>
          <% if current_user.role == 'administrador' %>
            <%= f.select :role, options_for_select([["Aluno", "aluno"], ["Professor", "professor"], ["Coordenador", "coordenador"], ["Administrador", "administrador"]], params[:role])%>
          <% elsif current_user.role == 'coordenador' %>
            <%= f.select :role, options_for_select([["Aluno", "aluno"], ["Professor", "professor"]], params[:role])%>
          <% end %>
        </div>
    <% end %>
    <%= f.submit :class => 'button right' %>
<% end %>
</div>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nome %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuario', new_user_path %>

app/views/users/new.html.erb
<div class="authform">
  <h1>New User</h1>
  <%= render 'form' %>
</div>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>