config/routes.rb
Rails.application.routes.draw do

  resources :arduino_clients
  resources :registration_courses
  resources :disciplines
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, except: [:create]
  resources :cursos
  resources :cameras

  root to: 'welcome#index'

  scope "/cameras/:id/" do
    get "camera_record", to: "cameras#record", as: :camera_record
    get "camera_record_start", to: "cameras#record_start", as: :camera_record_start
    get "camera_record_stop", to: "cameras#record_stop", as: :camera_record_stop
  end

  resources :disciplines do
    get :arduino
  end

  get 'welcome/index'

  get 'welcome/destroy'

  get 'welcome/edit'

  get 'welcome/show'

  post 'create_user' => 'users#create', as: :create_user

end

app/models/curso.rb
class Curso < ActiveRecord::Base
  belongs_to :coordenador, :class_name => 'User'
  has_one :users
  has_many :disciplines, :dependent => :destroy
  has_many :registration_courses, :dependent => :destroy

  validate :coordenador!

  def coordenador!
    if !self.coordenador_id.nil? or !self.coordenador_id.blank?
      if User.exists?(self.coordenador_id)
        coordenador = User.find(self.coordenador_id)
        if coordenador.role == 'coordenador'
          errors.delete(:coordenador)
          true
        else
          errors.add(:coordenador, "apenas.")
          false
        end
      else
        errors.add(:coordenador, "não existe.")
        false
      end
    else
      errors.add(:coordenador, "não pode ficar em branco.")
      false
    end
  end

  def count_workload
    workloads = 0.0
    self.disciplines.each do |discipline|
      workloads += discipline.workload
    end

    return workloads
  end
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
    authorize @curso
  end

  # GET /cursos/1/edit
  def edit
    authorize @curso
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)
    authorize @curso

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    authorize @curso
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    authorize @curso
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nome, :descricao, :coordenador_id, :disciplines)
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= form_for(@curso) do |f| %>
  <% if @curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% @curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :coordenador_id %><br>
    <%= f.text_field :coordenador_id %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form' %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<h1>Listing Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Coordenador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.nome %></td>
        <td><%= curso.coordenador.nome %></td>
        <td><%= link_to 'Show', curso %></td>
        <td><%= link_to 'Edit', edit_curso_path(curso) %></td>
        <td><%= link_to 'Destroy', curso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curso', new_curso_path %>

app/views/cursos/new.html.erb
<h1>New Curso</h1>

<%= render 'form' %>

<%= link_to 'Back', cursos_path %>

app/views/cursos/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @curso.nome %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @curso.descricao %>
</p>

<p>
  <strong>Carga Horaria Total:</strong>
  <%= @curso.count_workload %>
</p>

<p>
  <strong>Coordenador:</strong>
  <%= @curso.coordenador.nome %>
</p>

<p>
  <strong>Disciplinas:</strong>
  <% @curso.disciplines.each do |discipline| %>
    <a href="javascript: void(0)" onclick="showDiscipline('<%= discipline_path(discipline.id) %>')"><%= discipline.name %></a><br />
  <% end %>
</p>

<% if current_user != nil %>
  <p>
    <% if current_user.course_exists?(@curso.id) %>
      <button id="matricular_curso" class="btn" disabled="true" onclick="enrollCourse('<%= registration_courses_path %>', <%= @curso.id %>, <%= current_user.id %>);">Matricular-se</button>
    <% else %>
      <button id="matricular_curso" class="btn" onclick="enrollCourse('<%= registration_courses_path %>', <%= @curso.id %>, <%= current_user.id %>);">Matricular-se</button>
    <% end %>
  </p>
<% end %>

<div id="read_discipline">
  <strong>Carga Horaria</strong>
  <span id="read_workload"></span><br />
  <strong>Professor</strong>
  <span id="read_professor"></span><br />
  <strong>Descrição</strong>
  <span id="read_description"></span><br />
  <strong>Ementa</strong>
  <span id="read_ementa"></span><br />
  <strong>Bibliografia</strong>
  <span id="read_bibliography"></span>
</div>

<%= link_to 'Edit', edit_curso_path(@curso) %> |
<%= link_to 'Back', cursos_path %>