config/routes.rb
Rails.application.routes.draw do

  resources :arduino_clients
  resources :registration_courses
  resources :disciplines
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, except: [:create]
  resources :cursos
  resources :cameras

  root to: 'welcome#index'

  scope "/cameras/:id/" do
    get "camera_record", to: "cameras#record", as: :camera_record
    get "camera_record_start", to: "cameras#record_start", as: :camera_record_start
    get "camera_record_stop", to: "cameras#record_stop", as: :camera_record_stop
  end

  resources :disciplines do
    get :arduino
  end

  get 'welcome/index'

  get 'welcome/destroy'

  get 'welcome/edit'

  get 'welcome/show'

  post 'create_user' => 'users#create', as: :create_user

end

app/models/camera.rb
class Camera < ActiveRecord::Base
  belongs_to :curso
  belongs_to :user
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :set_camera, only: [:show, :edit, :update, :destroy, :record, :record_start, :record_stop]

  @@controls = Hash.new

  # GET /cameras
  # GET /cameras.json
  def index
    @cameras = Camera.all
  end

  # GET /cameras/1
  # GET /cameras/1.json
  def show
  end

  # GET /cameras/new
  def new
    @camera = Camera.new
  end

  # GET /cameras/1/edit
  def edit
  end

  # POST /cameras
  # POST /cameras.json
  def create
    @camera = Camera.new(camera_params)
    @camera.user_id = current_user.id

    respond_to do |format|
      if @camera.save
        format.html { redirect_to @camera, notice: 'Camera was successfully created.' }
        format.json { render :show, status: :created, location: @camera }
      else
        format.html { render :new }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cameras/1
  # PATCH/PUT /cameras/1.json
  def update
    respond_to do |format|
      if @camera.update(camera_params)
        format.html { redirect_to @camera, notice: 'Camera was successfully updated.' }
        format.json { render :show, status: :ok, location: @camera }
      else
        format.html { render :edit }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cameras/1
  # DELETE /cameras/1.json
  def destroy
    @camera.destroy
    respond_to do |format|
      format.html { redirect_to cameras_url, notice: 'Camera was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def record 
    

    @camera.disponivel = false

    respond_to do |format|
      if @camera.save
        format.html { render :record, notice: 'Camera está pronta para uso.' }
        format.json { render :record, status: :ok, location: @camera }
      else
        format.html { render :record }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end


  require 'streamio-ffmpeg'
 
  def record_start
    url_video = @camera.ip_video #"http://192.168.0.101:8080/video"
    url_audio = @camera.ip_audio #"http://192.168.0.101:8080/audio.wav"

    # tmp directory
    path = Rails.root.join('tmp')
    # create sub-directory as md5 hash based on URL
    sub_dir = Digest::MD5.hexdigest(url_video)
    # append sub_dir on the path
    destination_path = path.join(sub_dir) 
    timeout_in_seconds = 1

    puts params.to_json
    if !@@controls.key?(:users)
      @@controls[:users] = {}
    end 
    

    if !@@controls[:users].key?(current_user.id.to_s)
      @@controls[:users][current_user.id.to_s] = {}
    end

    if !@@controls[:users][current_user.id.to_s].key?(:camera)
      @@controls[:users][current_user.id.to_s][:camera] = {audio: [], video: []}
    end

    puts params.to_json

    #threads = []
    #threads = Thread.new { puts "Whats the big deal" }
    
    #puts @@controls[:users][current_user.id.to_s][:camera].to_json
    #@@controls[:users][current_user.id.to_s][:camera][:audio] << threads
    #puts @@controls[:users][current_user.id.to_s][:camera][:audio]

    @@controls[:users][current_user.id.to_s][:camera][:audio] = Thread.new do
      system("timeout -s KILL 30 wget --limit-rate=200000000k -P #{destination_path} #{url_audio} ")
    end

    @@controls[:users][current_user.id.to_s][:camera][:audio].run

    @@controls[:users][current_user.id.to_s][:camera][:video] = Thread.new do 
      system("timeout -s KILL 30 wget --limit-rate=200000000k -P #{destination_path} #{url_video} ")
    end

    puts "\nDone Video Download"

    respond_to do |format|      
      format.json { render json: {status: :gravando}, status: :ok }      
    end
  end

  def record_stop
    puts "ski"
    a = @@controls[:users][current_user.id.to_s][:camera][:audio]
    b = @@controls[:users][current_user.id.to_s][:camera][:video]
    a.run
    puts a
    puts a.status
    puts b
    puts b.status
    puts Thread.current 
    puts Thread.current.status
    #Thread.kill(a)
    #a.exit

    respond_to do |format|      
      format.json { render json: {status: :parou}, status: :ok }      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camera
      @camera = Camera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camera_params
      params.require(:camera).permit(:ip_video, :ip_audio, :disponivel, :sala, :horario_disponivel_inicial, :horario_disponivel_final, :curso_id, :user_id)
    end
end

app/views/cameras/_camera.html.erb
<table>
  <thead>
    <tr>
      <th>Ip video</th>
      <th>Ip audio</th>
      <th>Disponivel</th>
      <th>Sala</th>
      <th>Horario disponivel inicial</th>
      <th>Horario disponivel final</th>
      <th>Curso</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @cameras.each do |camera| %>
      <tr>
        <td><%= camera.ip_video %></td>
        <td><%= camera.ip_audio %></td>
        <td><%= camera.disponivel %></td>
        <td><%= camera.sala %></td>
        <td><%= camera.horario_disponivel_inicial %></td>
        <td><%= camera.horario_disponivel_final %></td>
        <td><%= camera.curso.nome %></td>
        <td><%= link_to 'Filmar', camera_record_path(camera) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cameras/_form.html.erb
<%= form_for(@camera) do |f| %>
  <% if @camera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camera.errors.count, "error") %> prohibited this camera from being saved:</h2>

      <ul>
      <% @camera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip_video %><br>
    <%= f.text_field :ip_video %>
  </div>
  <div class="field">
    <%= f.label :ip_audio %><br>
    <%= f.text_field :ip_audio %>
  </div>
  <div class="field">
    <%= f.label :disponivel %><br>
    <%= f.check_box :disponivel %>
  </div>
  <div class="field">
    <%= f.label :sala %><br>
    <%= f.text_field :sala %>
  </div>
  <div class="field">
    <%= f.label :horario_disponivel_inicial %><br>
    <%= f.datetime_select :horario_disponivel_inicial %>
  </div>
  <div class="field">
    <%= f.label :horario_disponivel_final %><br>
    <%= f.datetime_select :horario_disponivel_final %>
  </div>
  <div class="field">
    <%= f.label :curso_id %><br>
    <%= f.select :curso_id, Curso.all.collect {|c| [ c.nome, c.id ] }%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cameras/edit.html.erb
<h1>Editing Camera</h1>

<%= render 'form' %>

<%= link_to 'Show', @camera %> |
<%= link_to 'Back', cameras_path %>

app/views/cameras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cameras</h1>

<%= render 'camera' %>

<br>

<%= link_to 'New Camera', new_camera_path %>

app/views/cameras/new.html.erb
<h1>New Camera</h1>

<%= render 'form' %>

<%= link_to 'Back', cameras_path %>

app/views/cameras/record.html.erb
<a href="#" onclick="recordStart();">Iniciar Gravação</a>
<a href="#" onclick="recordStop();">Parar Gravação</a>

app/views/cameras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip video:</strong>
  <%= @camera.ip_video %>
</p>

<p>
  <strong>Ip audio:</strong>
  <%= @camera.ip_audio %>
</p>

<p>
  <strong>Disponivel:</strong>
  <%= @camera.disponivel %>
</p>

<p>
  <strong>Sala:</strong>
  <%= @camera.sala %>
</p>

<p>
  <strong>Horario disponivel inicial:</strong>
  <%= @camera.horario_disponivel_inicial %>
</p>

<p>
  <strong>Horario disponivel final:</strong>
  <%= @camera.horario_disponivel_final %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @camera.curso %>
</p>

<p>
  <strong>User:</strong>
  <%= @camera.user %>
</p>

<%= link_to 'Edit', edit_camera_path(@camera) %> |
<%= link_to 'Back', cameras_path %>