config/routes.rb
Rails.application.routes.draw do

  resources :arduino_clients
  resources :registration_courses
  resources :disciplines
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, except: [:create]
  resources :cursos
  resources :cameras

  root to: 'welcome#index'

  scope "/cameras/:id/" do
    get "camera_record", to: "cameras#record", as: :camera_record
    get "camera_record_start", to: "cameras#record_start", as: :camera_record_start
    get "camera_record_stop", to: "cameras#record_stop", as: :camera_record_stop
  end

  resources :disciplines do
    get :arduino
  end

  get 'welcome/index'

  get 'welcome/destroy'

  get 'welcome/edit'

  get 'welcome/show'

  post 'create_user' => 'users#create', as: :create_user

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Cursos', cursos_path %></li>
<li><%= link_to 'Disciplinas', disciplines_path %></li>
<li><%= link_to 'Usuarios', users_path %></li>
<li><%= link_to 'Cameras', cameras_path %></li> <!-- adicionar para o coordenador cadastrar depois e adm tbn -->
<li><%= link_to 'Meus Cursos', registration_courses_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Editar perfil', edit_user_path(current_user) %></li>
  <li><%= link_to 'Editar conta', edit_user_registration_path %></li>
  <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Cadastrar-se', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Portal" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Portal" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>